version: '3.8'

services:
  summarization-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: summarization-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Optional: mount code for live changes during development
    restart: unless-stopped
    # env_file:
    #   - .env

  streamlit-app:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - summarization-api
    restart: unless-stopped
